/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAlerts: typeof import('./src/components/appAlerts.vue')['default']
    Button: typeof import('./src/components/videoPlayerV2/controls/Button.vue')['default']
    Dashboard: typeof import('./src/components/dashboard/index.vue')['default']
    DatabaseStats: typeof import('./src/components/dashboard/widgets/DatabaseStats.vue')['default']
    Development: typeof import('./src/components/settings/development.vue')['default']
    Discord: typeof import('./src/components/settings/discord.vue')['default']
    ExtendedHistory: typeof import('./src/components/navigationDrawer/extendedHistory.vue')['default']
    ExternalLink: typeof import('./src/components/externalLink.vue')['default']
    General: typeof import('./src/components/settings/general.vue')['default']
    Integrations: typeof import('./src/components/settings/integrations.vue')['default']
    LastSeen: typeof import('./src/components/dashboard/widgets/LastSeen.vue')['default']
    Main: typeof import('./src/components/navigationDrawer/main.vue')['default']
    RecentlyAdded: typeof import('./src/components/dashboard/widgets/RecentlyAdded.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDialog: typeof import('./src/components/searchDialog.vue')['default']
    ShortcutsOverview: typeof import('./src/components/videoPlayerV2/shortcutsOverview.vue')['default']
    Spinner: typeof import('./src/components/spinner.vue')['default']
    Toolbar: typeof import('./src/components/toolbar.vue')['default']
    VideoPlayerV2: typeof import('./src/components/videoPlayerV2/index.vue')['default']
    Volume: typeof import('./src/components/videoPlayerV2/controls/Volume.vue')['default']
    WatchNav: typeof import('./src/components/watchNav.vue')['default']
    WidgetWrapper: typeof import('./src/components/dashboard/WidgetWrapper.vue')['default']
  }
}
